<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
<title>Rede WEBECARD.net</title>
<meta name="description" content="A WEBECARD.net é um site promocional que realiza a venda de cartões virtuais, os E-Cards. Eles possuem diversos designs e cada um possui um código promocional que permite concorrer a 2 Sorteios, além de outros recursos extras." />
<meta name="keywords" content="Promoções, Sorteios" />
<meta name="robots" content="index, follow" />
<!-- META Tags generated by http://www.submitexpress.com/meta-tags-generator.html -->

<link rel="stylesheet" type="text/css" href="http://www.webecard.net/assets/css/main.css" />


    <!-- bjqs.css contains the *essential* css needed for the slider to work -->
    <link rel="stylesheet" href="http://www.webecard.net/assets/css/bjqs.css">

    <!-- load jQuery and the plugin -->
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="http://www.webecard.net/assets/js/bjqs-1.3.js"></script>



</head>

<body>

   <!-- Begin Wrapper -->
   <div id="wrapper">
   
         <!-- Begin Header -->
         <div id="header">		
		 
		 		 
			<div id="logo">
			<!-- WEB<span style='color:orange;'>ECARD</span><span class='logorede'>.net</span> <br> -->
			<a href="http://www.webecard.net/" ><img src="http://www.webecard.net/assets/images/logo.jpg" alt='WEBECARD.net'></a>
			</div>
			
			<div id="logged">
			<a href='http://www.webecard.net/index.php/main/login'>Entrar</a> / <a href='http://www.webecard.net/index.php/main/signup_basic'>Criar Conta</a>			</div>
			
			<div id="lang">
			<a href='http://www.webecard.net/index.php/main/set_lang/en'><img src="http://www.webecard.net/assets/images/uk_cru.png" alt='English' width='25' ></a>
			<a href='http://www.webecard.net/index.php/main/set_lang/br'><img src="http://www.webecard.net/assets/images/br_cru.png" alt='Português' width='25' ></a>		
			</div>
			
			<div id="menu3">
			<div class="underlinemenu">
			<ul>
			<li><a href="http://www.webecard.net/index.php/main/company" class=''>A WEBECARD.net</a></li> 
			<li><a href="http://www.webecard.net/index.php/main/funciona" class=''>Como Funciona</a></li> 
			<li><a href="http://www.webecard.net/index.php/main/perg_resp" class=''>Perguntas & Respostas</a></li> 
			</ul>
			</div>
			</div>

			
			<div id="menu1">
			<div class="underlinemenu">
			<ul>
			<li><a href="http://www.webecard.net/" class='selected'>Home</a></li> 
			<li><a href="http://www.webecard.net/index.php/main/meus_ecards" class=''>Meus E-Cards</a></li> 
			<li><a href="http://www.webecard.net/index.php/main/meu_fin" class=''>Meus Pontos</a></li> 
			<li><a href="http://www.webecard.net/index.php/main/minha_rede" class=''>Minha Rede</a></li> 
			<li><a href="http://www.webecard.net/index.php/main/ecardscheck" class=''>Checar E-cards</a></li> 
			</ul>
			</div>
			</div>
			 
		 </div>
		 <!-- End Header -->
	﻿<div id='menu2'>
<div class="underlinemenu">

<ul>
<li> <a href="http://www.webecard.net/index.php/main/meus_ecards/ativos" class='selected'>Ativos</a> </li>
<li> <a href="http://www.webecard.net/index.php/main/meus_ecards/terminados" class=''>Terminados</a> </li>
<li> <a href="http://www.webecard.net/index.php/main/novos_ecards" class=''>Novo E-Card</a> </li>
</ul>
</div>

<div class="underlinemenu2">
<ul>
<li> <a href="http://www.webecard.net/index.php/main/meus_ecards/distribuicao" class=''>E-Cards Divulgação</a> </li>
<li> <a href="http://www.webecard.net/index.php/main/ecards_divu" class=''>Novo E-Card Divulgação</a> </li>
<li> <a href="http://www.webecard.net/index.php/main/printer" class=''>Imprimir</a> </li>
</ul>
</div>
</div>
<div id='ecards_title'>
<h1>Meus E-Cards</h1>
</div>
<div id='faux'>

    <h3>Obrigado por efetuar a compra.</h3>
    <h3><?php echo $_GET['TransacaoID']; ?></h3>



</div>



         <!-- Begin Footer -->
         <div id="footer" style="background:#000 url('http://www.webecard.net/assets/images/bgfooter.jpg') top repeat-x;" >
		       
        <div id='f_float_logo'>
      	
			WEB<span style='color:orange;'>ECARD</span><span class='logorede'>.net</span>

        </div>
		
        <div id='f_float'>
		<a href="http://www.webecard.net/index.php/main/company" class=''>
		Perguntas & Respostas</a>
        </div>
		
        <div id='f_float'>
      	<a href="http://www.webecard.net/index.php/main/funciona" class=''>
		Como Funciona</a> 
        </div>
		
        <div id='f_float'>
		<a href="http://www.webecard.net/index.php/main/contato" class=''> 
		Contato</a>
        </div>
		
        <div id='f_float_l'>
      	
		<img src="http://www.webecard.net/assets/images/licence.jpg" alt='E-Gambling Licence'>
        </div>
		
		
         </div>
		 <!-- End Footer -->
		 
   </div>
   <!-- End Wrapper -->
</body>
</html>

