<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
<title>Rede WEBECARD.net  <?php //echo $_title; ?></title>
<meta name="description" content="A WEBECARD.net é um site promocional que realiza a venda de cartões virtuais, os E-Cards. Eles possuem diversos designs e cada um possui um código promocional que permite concorrer a 2 Sorteios, além de outros recursos extras." />
<meta name="keywords" content="Promoções, Sorteios" />
<meta name="robots" content="index, follow" />
<!-- META Tags generated by http://www.submitexpress.com/meta-tags-generator.html -->

<link rel="stylesheet" type="text/css" href="<?php echo asset_url();?>css/main.css" />

<?php if (isset($flash)): ?>

    <!-- bjqs.css contains the *essential* css needed for the slider to work -->
    <link rel="stylesheet" href="<?php echo asset_url();?>css/bjqs.css">

    <!-- load jQuery and the plugin -->
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="<?php echo asset_url();?>js/bjqs-1.3.js"></script>

<?php endif; ?>

<?php if (isset($form_val)): ?>
<script src="<?php echo asset_url();?>js/jquery-1.10.1.min.js"></script>
<script src="<?php echo asset_url();?>js/highlight.pack.js"></script>
<script src="<?php echo asset_url();?>js/jquery.checkboxes.min.js"></script>

<script src="<?php echo asset_url();?>js/jquery.tipsy.js"></script>

<link rel="stylesheet" type="text/css" href="<?php echo asset_url();?>css/tipsy.css" />
<link rel="stylesheet" type="text/css" href="<?php echo asset_url();?>css/tipsy-docs.css" />

<script type="text/javascript">   
  $(function() {
    $('#form1').tipsy({gravity: 'ne'});
    $('#form2').tipsy({gravity: 'ne'});
    $('#form3').tipsy({gravity: 'ne'});
    $('#form4').tipsy({gravity: 'ne'});
    $('#form5').tipsy({gravity: 'ne'});
    $('#form6').tipsy({gravity: 'ne'});
    $('#form7').tipsy({gravity: 'ne'});
    $('#form8').tipsy({gravity: 'ne'});
    $('#form9').tipsy({gravity: 'ne'});
    $('#form10').tipsy({gravity: 'ne'});
  });
</script>
<?php endif; ?>

<?php if (isset($n_e_header)): ?>
<script type="text/javascript"> 
jQuery(function($) {
    $('#table5').checkboxes('max', 5);
});

$(function(){
    $( ".class_chk" ).on( "click", function(){
        if($(this).is(':checked'))
            $(this).parent().css({"background-color":"#cd0000", "color":"#FFF"});
        else
            $(this).parent().css({"background-color":"#FFF", "color":"#000"});
    });
});

function reloadPage()
  {
  location.reload();
  }
  
  $(function() {
    $('#divu1').tipsy({gravity: 'ne'});
    $('#divu2').tipsy({gravity: 'ne'});
    $('#divu3').tipsy({gravity: 'ne'});
    $('#divu4').tipsy({gravity: 'ne'});
  });
</script>
<?php endif; ?>

</head>

<body>

   <!-- Begin Wrapper -->
   <div id="wrapper">
   
         <!-- Begin Header -->
         <div id="header">		
		 
		<?php 
		//echo "<div style='position:fixed; z-index:999; margin:500px 0 0 0; background-color:red; color:white; padding:3px; font-size:14px; font-weight:bold; line-height:150%;'>";	
		//print_r($this->session->all_userdata()); 		 echo "</div>"; 	 
		 ?>
		 
			<div id="logo">
			<!-- WEB<span style='color:orange;'>ECARD</span><span class='logorede'>.net</span> <br> -->
			<a href="<?php echo base_url(); ?>" ><img src="<?php echo base_url(); ?>assets/images/logo.jpg" alt='Rede WEBECARD.net'></a>
			</div>
			
			
			<?php 				
			
				if ($this->session->userdata('is_logged_in') == 1) {
				
					echo "<div id='logged'>Olá: <strong>";
					echo $this->session->userdata('log_user_name');
					echo "</strong> / ";
					echo "<a href='" . base_url() . "index.php/main/logout'>" . $_sair . "</a>";
					echo "</div>";
				} else {
				
					echo "<div id='notlogged'>";
//echo "<a href='" . base_url() . "index.php/main/login'>" . $_entrar . "</a>";
echo "<a href='" . base_url() . "index.php/main/login'><img src='" . base_url() . "assets/images/" . $_entrar_sml . "' alt='$_entrar' height='30' ></a>";	
echo " ";
//echo " / ";
//echo "<a href='" . base_url() . "index.php/main/signup_basic'>" . $_criar_conta . "</a>";				
echo "<a href='" . base_url() . "index.php/main/signup_basic'><img src='" . base_url() . "assets/images/" . $_signup_sml . "' alt='$_criar_conta' height='30' ></a>";	
					echo "</div>";
				}			
			?>
			
			
			<div id="lang">
			<a href='<?php echo base_url(); ?>index.php/main/set_lang/en'><img src="<?php echo base_url(); ?>assets/images/uk_cru.png" alt='English' ></a>
			<a href='<?php echo base_url(); ?>index.php/main/set_lang/br'><img src="<?php echo base_url(); ?>assets/images/br_cru.png" alt='Português' ></a>		
			</div>
			
			<div id="menu3">
			<div class="underlinemenu">
			<ul>
			<li><a href="<?php echo base_url(); ?>index.php/main/company" class='<?php if(isset($s_selected4)) echo $s_selected4; ?>'><?php echo $_company; ?></a></li> 
			<li><a href="<?php echo base_url(); ?>index.php/main/funciona" class='<?php if(isset($s_selected2)) echo $s_selected2; ?>'><?php echo $_funciona; ?></a></li> 
			<li><a href="<?php echo base_url(); ?>index.php/main/perg_resp" class='<?php if(isset($s_selected1)) echo $s_selected1; ?>'><?php echo $_faq; ?></a></li> 
			</ul>
			</div>
			</div>

			
			<div id="menu1">
			<div class="underlinemenu">
			<ul>
			<li><a href="<?php echo base_url(); ?>" class='<?php if(isset($selected1)) echo $selected1; ?>'>Home</a></li> 
			<li><a href="<?php echo base_url(); ?>index.php/main/meus_ecards" class='<?php if(isset($selected2)) echo $selected2; ?>'><?php echo $_meus_ecards; ?></a></li> 
			<li><a href="<?php echo base_url(); ?>index.php/main/meu_fin" class='<?php if(isset($selected3)) echo $selected3; ?>'><?php echo $_meu_fin; ?></a></li> 
			<li><a href="<?php echo base_url(); ?>index.php/main/minha_rede" class='<?php if(isset($selected4)) echo $selected4; ?>'><?php echo $_minha_rede; ?></a></li> 
			<li><a href="<?php echo base_url(); ?>index.php/main/ecardscheck" style='background-color:black; color:white;' ><?php echo $_ecardscheck; ?></a></li> 
			</ul>
			</div>
			</div>
			 
		 </div>
		 <!-- End Header -->
	